version: "3"
services:
  postgres:
    image: postgres:16
    container_name: postgres
    command: ["postgres", "-c", "wal_level=logical"]
    ports:
      - 5432:5432
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: develop
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: password
      PGUSER: develop
      TZ: Australia/Sydney
  debezium:
    image: debezium/server:3.0.0.Final
    container_name: debezium
    volumes:
      - ./config/debezium:/debezium/config
    depends_on:
      - postgres
    restart: always
  pubsub:
    image: google/cloud-sdk:497.0.0-emulators
    container_name: pubsub
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"

volumes:
  postgres_data:
    driver: local
    name: postgres_data
